import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";
import AboutSection from "./components/AboutSection";
import Navigation from "./components/Navigation";
import PageFooter from "./components/PageFooter";
import PageHeader from "./components/PageHeader";

const Home: NextPage = () => {
  const [open, setOpen] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Išjausk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://www.w3schools.com/w3css/4/w3.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>

      <Navigation
        openNavigation={open}
        closeNavigation={() => setOpen(false)}
      ></Navigation>

      <div className="w3-main w3-padding-large" style={{ marginLeft: "40%" }}>
        <span
          className="w3-button w3-top w3-white w3-xxlarge w3-text-grey w3-hover-text-black"
          style={{ width: "auto", right: "0" }}
          onClick={() => setOpen(true)}
        >
          <i className="fa fa-bars"></i>
        </span>
        <PageHeader></PageHeader>

        <div className="w3-padding-32 w3-content" id="portfolio">
          <h2 className="w3-text-grey">My Portfolio</h2>
          <hr className="w3-opacity"></hr>

          <div className="w3-row-padding" style={{ margin: "0 -16px" }}>
            <div className="w3-half">
              {/* <Image src="/w3images/wedding.jpg" width={"100%"}></Image>
              <Image src="/w3images/rocks.jpg" width={"100%"}></Image>
              <Image src="/w3images/sailboat.jpg" width={"100%"}></Image> */}
            </div>

            <div className="w3-half">
              {/* <Image src="/w3images/underwater.jpg" width={"100%"}></Image>
              <Image src="/w3images/chef.jpg" width={"100%"}></Image>
              <Image src="/w3images/wedding.jpg" width={"100%"}></Image>
              <Image src="/w3images/p6.jpg" width={"100%"}></Image> */}
            </div>
          </div>
        </div>
        <AboutSection></AboutSection>
        <PageFooter></PageFooter>
      </div>
    </div>
  );
};

export default Home;
